# Generated by Django 3.2 on 2022-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
        ),
    ]
