# Generated by Django 3.2 on 2022-09-22 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_magazine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ('-created',), 'verbose_name': 'Magazine', 'verbose_name_plural': 'Magazines'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
