# Generated by Django 3.2 on 2022-10-05 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20221005_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid_field',
            field=models.UUIDField(db_index=True, default=uuid.UUID('61b622b0-a410-435d-a998-3150695065bb'), unique=True, verbose_name='uuid field'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
