# Generated by Django 3.2 on 2022-10-05 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20221005_1548'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid_field',
            field=models.UUIDField(db_index=True, default=uuid.UUID('71a2abbf-11cc-4eda-a7d7-5044150fde46'), unique=True, verbose_name='uuid field'),
        ),
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='discount')),
                ('expire_time', models.DateTimeField(verbose_name='expire time')),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'Plan Discount',
                'verbose_name_plural': 'Plan Discounts',
            },
        ),
    ]
