# Generated by Django 3.2 on 2022-10-05 16:52

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20221005_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 16, 52, 15, 957876)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid_field',
            field=models.UUIDField(db_index=True, default=uuid.UUID('79af8cd1-1846-4d2e-8261-60ec6f2c2efa'), unique=True, verbose_name='uuid field'),
        ),
    ]
