# Generated by Django 3.2 on 2022-10-05 16:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20221005_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='need_checkout',
        ),
        migrations.AddField(
            model_name='payment',
            name='need_check',
            field=models.BooleanField(default=False, verbose_name='need check'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 16, 53, 7, 830800), verbose_name='expire time'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid_field',
            field=models.UUIDField(db_index=True, default=uuid.UUID('332e9334-1b43-40b7-ba2f-dc05ed3702ed'), unique=True, verbose_name='uuid field'),
        ),
    ]
