# Generated by Django 3.2 on 2022-10-05 17:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20221005_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 16, 43, 527111), verbose_name='expire time'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid field'),
        ),
    ]
