# Generated by Django 3.2 on 2022-10-05 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20221005_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='logs',
            field=models.TextField(default='dsfs', verbose_name='logs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 27, 0, 384168), verbose_name='expire time'),
        ),
    ]
