# Generated by Django 3.2 on 2022-10-05 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20221005_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 31, 25, 65117), verbose_name='expire time'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='logs'),
        ),
    ]
