# Generated by Django 3.2 on 2022-11-18 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20221014_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 23, 41, 7, 230499), verbose_name='expire time'),
        ),
    ]
