# Generated by Django 3.2 on 2022-11-19 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_payment_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 2, 47, 48, 374913), verbose_name='expire time'),
        ),
    ]
