# Generated by Django 3.2 on 2022-12-11 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_payment_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 22, 36, 4, 627895), verbose_name='expire time'),
        ),
    ]
