# Generated by Django 3.2 on 2022-11-19 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='jti')),
                ('token', models.TextField(verbose_name='token')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('expire_time', models.DateTimeField(verbose_name='expire time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Outstanding Token',
                'verbose_name_plural': 'Outstanding Tokens',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='blacklist at')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.outstandingtoken', verbose_name='token')),
            ],
            options={
                'verbose_name': 'Blacklist Token',
                'verbose_name_plural': 'Blacklist Tokens',
            },
        ),
    ]
