# Generated by Django 3.2 on 2022-09-02 09:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
