# Generated by Django 3.2 on 2022-12-11 22:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpremium'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid')),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 22, 36, 4, 616115), verbose_name='expire time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Forget Password',
                'verbose_name_plural': 'User Forget Passwords',
                'ordering': ('-expire_time',),
            },
        ),
    ]
