# Generated by Django 3.2 on 2022-09-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image_cover', models.ImageField(upload_to='', verbose_name='image cover')),
                ('image_background', models.ImageField(upload_to='', verbose_name='image background')),
                ('publish_at', models.DateField(verbose_name='publish_at')),
                ('created_at', models.DateField(verbose_name='created at')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'film'), (2, 'series')], default=1, verbose_name='type')),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, 'کیفیت اصلی'), (2, 'کیفیت پرده')], default=1, verbose_name='quality')),
                ('time_in_minutes', models.PositiveIntegerField(verbose_name='time in minutes')),
                ('ages', models.PositiveSmallIntegerField(verbose_name='ages')),
                ('country', models.CharField(choices=[('afghanistan', 'افغانستان'), ('argentina', 'آرژانتین'), ('austria', 'استرالیا'), ('azerbaijan', 'آذربایجان'), ('belgium', 'بلژیک'), ('cameroon', 'کامرون'), ('canada', 'کانادا'), ('chile', 'شیلی'), ('china', 'چین'), ('colombia', 'کلمبیا'), ('denmark', 'دانمارک'), ('egypt', 'مصر'), ('finland', 'فنلاند'), ('france', 'فرانسه'), ('germany', 'آلمان'), ('hungary', 'مجارستان'), ('indonesia', 'اندونیزیا'), ('iran', 'ایران'), ('iraq', 'عراق'), ('italy', 'ایتالیا'), ('japan', 'ژاپن'), ('mexico', 'مکزیک'), ('morocco', 'مراکش'), ('nepal', 'نپال'), ('netherlands', 'ایرلند'), ('poland', 'پولند'), ('russia', 'روسیه'), ('sweden', 'سوئد'), ('thailand', 'تایلند'), ('turkey', 'ترکیه'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('vietnam', 'ویتنام')], max_length=34, verbose_name='country')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='SeriesSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField(verbose_name='season')),
                ('name', models.CharField(max_length=120)),
                ('image_background', models.ImageField(upload_to='', verbose_name='image background')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.movie', verbose_name='series')),
            ],
            options={
                'verbose_name': 'Series Season',
                'verbose_name_plural': 'Series Seasons',
                'ordering': ('season',),
            },
        ),
        migrations.CreateModel(
            name='SeasonPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('part', models.PositiveSmallIntegerField(verbose_name='part')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='movie.seriesseason', verbose_name='Season Part')),
            ],
            options={
                'verbose_name': 'Season Part',
                'verbose_name_plural': 'Season Parts',
                'ordering': ('part',),
            },
        ),
        migrations.CreateModel(
            name='PartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('quality', models.IntegerField(verbose_name='quality')),
                ('volume', models.CharField(max_length=34)),
                ('link', models.CharField(max_length=240)),
                ('season_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='movie.seasonpart', verbose_name='part link')),
            ],
            options={
                'verbose_name': 'Part Link',
                'verbose_name_plural': 'Part Links',
                'ordering': ('quality',),
            },
        ),
        migrations.CreateModel(
            name='FilmLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('quality', models.IntegerField(verbose_name='quality')),
                ('volume', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=240)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='movie.movie')),
            ],
            options={
                'verbose_name': 'Film Link',
                'verbose_name_plural': 'Film Links',
                'ordering': ('quality',),
            },
        ),
        migrations.CreateModel(
            name='FilmMovie',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='SeriesMovie',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movie.movie',),
        ),
    ]
