# Generated by Django 3.2 on 2022-09-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='moviecomment',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='moviereview',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='filmsubtitle',
            name='language',
            field=models.CharField(choices=[('afghanistan', 'افغانستان'), ('argentina', 'آرژانتین'), ('austria', 'استرالیا'), ('azerbaijan', 'آذربایجان'), ('belgium', 'بلژیک'), ('cameroon', 'کامرون'), ('canada', 'کانادا'), ('chile', 'شیلی'), ('china', 'چین'), ('colombia', 'کلمبیا'), ('denmark', 'دانمارک'), ('egypt', 'مصر'), ('finland', 'فنلاند'), ('france', 'فرانسه'), ('germany', 'آلمان'), ('hungary', 'مجارستان'), ('indonesia', 'اندونیزیا'), ('iran', 'ایران'), ('iraq', 'عراق'), ('italy', 'ایتالیا'), ('japan', 'ژاپن'), ('mexico', 'مکزیک'), ('morocco', 'مراکش'), ('nepal', 'نپال'), ('netherlands', 'ایرلند'), ('poland', 'پولند'), ('russia', 'روسیه'), ('sweden', 'سوئد'), ('thailand', 'تایلند'), ('turkey', 'ترکیه'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('vietnam', 'ویتنام'), ('spain', 'اسپانیا')], default='iran', max_length=32, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('afghanistan', 'افغانستان'), ('argentina', 'آرژانتین'), ('austria', 'استرالیا'), ('azerbaijan', 'آذربایجان'), ('belgium', 'بلژیک'), ('cameroon', 'کامرون'), ('canada', 'کانادا'), ('chile', 'شیلی'), ('china', 'چین'), ('colombia', 'کلمبیا'), ('denmark', 'دانمارک'), ('egypt', 'مصر'), ('finland', 'فنلاند'), ('france', 'فرانسه'), ('germany', 'آلمان'), ('hungary', 'مجارستان'), ('indonesia', 'اندونیزیا'), ('iran', 'ایران'), ('iraq', 'عراق'), ('italy', 'ایتالیا'), ('japan', 'ژاپن'), ('mexico', 'مکزیک'), ('morocco', 'مراکش'), ('nepal', 'نپال'), ('netherlands', 'ایرلند'), ('poland', 'پولند'), ('russia', 'روسیه'), ('sweden', 'سوئد'), ('thailand', 'تایلند'), ('turkey', 'ترکیه'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('vietnam', 'ویتنام'), ('spain', 'اسپانیا')], max_length=34, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonpartsubtitle',
            name='language',
            field=models.CharField(choices=[('afghanistan', 'افغانستان'), ('argentina', 'آرژانتین'), ('austria', 'استرالیا'), ('azerbaijan', 'آذربایجان'), ('belgium', 'بلژیک'), ('cameroon', 'کامرون'), ('canada', 'کانادا'), ('chile', 'شیلی'), ('china', 'چین'), ('colombia', 'کلمبیا'), ('denmark', 'دانمارک'), ('egypt', 'مصر'), ('finland', 'فنلاند'), ('france', 'فرانسه'), ('germany', 'آلمان'), ('hungary', 'مجارستان'), ('indonesia', 'اندونیزیا'), ('iran', 'ایران'), ('iraq', 'عراق'), ('italy', 'ایتالیا'), ('japan', 'ژاپن'), ('mexico', 'مکزیک'), ('morocco', 'مراکش'), ('nepal', 'نپال'), ('netherlands', 'ایرلند'), ('poland', 'پولند'), ('russia', 'روسیه'), ('sweden', 'سوئد'), ('thailand', 'تایلند'), ('turkey', 'ترکیه'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('vietnam', 'ویتنام'), ('spain', 'اسپانیا')], default='iran', max_length=32, verbose_name='language'),
        ),
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='movie.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
