# Generated by Django 3.2 on 2022-09-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='movie.moviecomment', verbose_name='parent'),
        ),
    ]
