# Generated by Django 3.2 on 2022-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220925_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieview',
            options={'verbose_name': 'Movie View', 'verbose_name_plural': 'Movie Views'},
        ),
        migrations.CreateModel(
            name='SliderMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Slider Movie',
                'verbose_name_plural': 'Slider Movies',
                'ordering': ('-created',),
            },
        ),
    ]
