# Generated by Django 3.2 on 2022-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_moviecomment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='subject',
            field=models.CharField(default='salam', max_length=120, verbose_name='subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='rate'),
        ),
    ]
