# Generated by Django 3.2 on 2022-09-27 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220927_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieview',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
