# Generated by Django 3.2 on 2022-12-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecommentdislike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='movie.moviecomment', verbose_name='dislike'),
        ),
    ]
